# Action to start a rodney mission
# Goal including goal mission constants
uint8  TAKE_A_MESSAGE = 0
uint8  BORD           = 1
uint8  LINE_UP        = 2
uint8  mission_id         # ID for which mission to run
string mission_parameters # Parameters for the mission
--- 
# No result parameters
---
# No feedback parameters
